

---
title: "Variance in Condition vs Nest Size"
author: "Ruth Sharpe"
date: "`r format(Sys.time(), '%d %B, %Y')`"
geometry: margin=1cm

---

AIC Values of all possible models with instar included
------------------


```{r kable, results='asis',  echo = FALSE}
#pander options http://rapporter.github.io/pander/#general-options
myData <- condVar


outcome    <- c("relativeVar")
predictors <- c("logCtFm", "logCtFm:Instar", "I(logCtFm^2)", "I(logCtFm^2):Instar")
dataset    <- myData

modTable <- allModelsAIC(outcome, predictors, dataset)

row.names(modTable) <- NULL # removing row names

panderOptions('table.split.table', Inf)
panderOptions('round', 2)
panderOptions('keep.trailing.zeros', TRUE)
panderOptions('keep.line.breaks', TRUE)


pander(modTable,  row.names = NULL, justify = 'left', split.cells = c(1, 2, 61, 2))

	
```



Graph with lowest AIC model superimposed
------------------
 

```{r, fig.height=8, fig.width=12, echo = FALSE}
FullModel <- lmer(relativeVar~ logCtFm + Instar + (1|NestID), data = myData, REML = FALSE)

InstarGridGraph(myData, "relativeVar", "Variance in Condition", "n", "", FullModel)

```


Statistics using model without squared values as the full model (Lowest AIC Model)
====================


```{r Stats,  results='asis', echo = FALSE , comment = "", message = FALSE, warning = FALSE}


TestInstar <- c( "Testing Instar Term", lmer(relativeVar~ logCtFm + (1|NestID), data = myData, REML = FALSE) , data = myData, REML = FALSE)
TestNestSize <- c("Testing Nest Size", lmer(relativeVar~ Instar + (1|NestID), data = myData, REML = FALSE) , data = myData, REML = FALSE)


RedModels <- list(TestInstar, TestNestSize)

MRAnovaFun(FullModel, RedModels)

cat("Note: See next page for graph")

```


Graph of condition variance against instar
====================

```{r, fig.height=6, fig.width=8, echo = FALSE}
ggplot(data = condVar, aes(x = Instar, y = relativeVar, fill = InstarSex)) +
	labs(x = "Instar") + labs(y = "Variance in Condition") + geom_boxplot() + mytheme

```
