---
title: "Chapter "
author: "Ruth Sharpe"
date: "`r format(Sys.time(), '%d %B, %Y')`"
---

```{r docSettings, include = FALSE}
## Make sure to run R code /CurrentPaperCode_9Aug/_RUNFIRST
library(ggplot2)
library(plyr)
library(lme4)
knitr::opts_chunk$set(echo = FALSE, comment = "", message = FALSE, warning = FALSE)


#bootSamples <- read.csv("G:/Dropbox/RuthEcuador2013/NestSize/bootSamplesDolph_9June.csv")

bootSamples <- read.csv("C:/Users/Ruth/Dropbox/RuthEcuador2013/NestSize/bootSamplesDolph_9June.csv")

bootSummy <- ddply(bootSamples, .(SampleID, SampleSize), summarise,
		N    = sum(!is.na(Value)),
		mean = mean(Value, na.rm=TRUE),
		sd   = sd(Value, na.rm=TRUE),
		sampVar = var(Value),
		cv = sd/mean,
		cv_coor = (1+ (1/4*N) * cv)

)



mytheme <-theme_bw(base_size=15)  + theme(plot.title = element_text(vjust=2, size = 8), 
		panel.border = element_rect(fill = NA, colour = "grey", linetype=1, size = 1), 
		panel.grid.minor = element_blank())

```



```{r graphSmplSizevsCV}

# N vs cv

ggplot(bootSummy, aes(x = N, y = cv)) + geom_point(size = 1, shape = "a") + 
		geom_smooth(method='lm',formula=y~x, se = FALSE, colour = "black", size = 0.5 ) + mytheme +
		xlab("sample size") + ylab("coefficient of variation")

lmTest <- lm(cv ~ mean + I(mean ^ 2) + N, data = bootSummy)

lmRed <- lm(cv ~ mean + I(mean ^ 2), data = bootSummy)

anova(lmTest, lmRed)


```

figure x: sample size against cv

```{r graphMeanevsCV}

# mean vs cv

ggplot(bootSummy, aes(x = mean, y = cv)) + 
		xlab("sample mean") + ylab("coefficient of variation") +
		geom_point(size = 1, shape = "a") + 
		geom_smooth(method='lm',formula=y~x + I(x^2), se = FALSE, colour = "black", size = 0.5 ) + mytheme



lmRed <- lm(cv ~  N, data = bootSummy)

anova(lmTest, lmRed)

```

figure x: mean against cv



```{r bootVarN}
#boot_var <- read.csv("G:/Dropbox/RuthEcuador2013/NestSize/Dolph_bootVars.csv")

boot_var <- read.csv("C:/Users/Ruth/Dropbox/RuthEcuador2013/NestSize/Dolph_bootVars.csv")
v
# N vs cv

ggplot(boot_var, aes(x = N, y = bootSD_var)) +  xlab("sample size") + ylab("Bootstrap disparity index") +
		geom_point(size = 1, shape = "a") + 
		geom_smooth(method='lm',formula=y~x, se = FALSE, colour = "black", size = 0.5 ) + mytheme


lmTest <- lm(bootSD_var ~ N + data_mean, data = boot_var)

lmRed <- lm(bootSD_var ~ data_mean, data = boot_var)

anova(lmTest, lmRed)


```
figure x: my boot variance against sample size

```{r bootVarMean}

ggplot(boot_var, aes(x = data_mean, y = bootSD_var)) + geom_point(size = 1, shape = "a") + 
		xlab("sample mean") + ylab("Bootstrap disparity index") +
		geom_smooth(method='lm',formula=y~x, se = FALSE, colour = "black", size = 0.5 ) + mytheme

lmTest <- lm(bootSD_var ~ data_mean + N, data = boot_var)

lmRed <- lm(bootSD_var ~ N, data = boot_var)

anova(lmTest, lmRed)




```

figure x: my boot variance against mean of sample