


---
title: "Condition vs Nest Size Up Step model addition"
author: "Ruth Sharpe"
date: "Run on `r format(Sys.time(), '%d %B, %Y')` at `r Sys.time()`"
geometry: margin=1cm
header-includes:
    - \usepackage{float}
---

```{r dataImport,  include = FALSE}
knitr::opts_chunk$set(echo = FALSE, comment = "", message = FALSE)
options(xtable.comment = FALSE, xtable.table.placement="H")

dataset <- spidersMul



```

Model Addition
=====================


```{r kable, results='asis',  echo = FALSE, warning = FALSE, message = FALSE, comment = FALSE}
#pander options http://rapporter.github.io/pander/#general-options

upStepWiseLmer(spidersMul, "condResiduals", forPDF = "y")

finalModel <- "condResiduals ~ logCtFm + InstarNumber + (1 | NestID)"

cat("Final model is ", finalModel)

final_lmer <- lmer(as.formula(finalModel),
		dataset, REML = FALSE)


#anova(final_lmer)
	
```

\pagebreak


Checking full model fit
--------------------


```{r ModelFit, fig.height=4, fig.width=4} 

model_Check(final_lmer)


```



Graph with full model superimposed
====================
 

```{r Graph, fig.height=7, fig.width=13}


cat("Model:", finalModel, sep = '\n')

InstarGridGraph(dataset, "condResiduals", "Condition", model = final_lmer)

```



