

---
title: "Leg Length vs Nest Size"
author: "Ruth Sharpe"
date: "`r format(Sys.time(), '%d %B, %Y')`"

---

AIC Values of all possible models with instar included
------------------
(note: If include models without instar as a factor the results seem strange and
no significance to lowest AIC model as it doesn't have instar)


```{r kable, results='asis',  echo = FALSE}
#pander options http://rapporter.github.io/pander/#general-options
row.names(legLegAllMods) <- NULL # removing row names

panderOptions('table.split.table', Inf)
panderOptions('digits', 4)
panderOptions('keep.line.breaks', TRUE)


pander(legLegAllMods,  row.names = NULL, justify = 'left', split.cells = c(2, 60, 2))

	
```



Graph with lowest AIC model superimposed
------------------
 

```{r, fig.height=8, fig.width=13, echo = FALSE}

InstarGridGraph(spidersMul, "logLeg", "Leg Length - log transformed", "n", "LegLengthvsNestSize_by_Instar_ZGSA", legLmFull)

```

Statistics of lowest AIC model
------------------



```{r xtable,  echo = FALSE}
##https://cran.r-project.org/web/packages/xtable/xtable.pdf
myFormula1 <- as.character(legLmFull@call[2])
myFormulaRed <- as.character(legLmRed@call[2])
cat(paste("Anova of full model by itself. Model:", myFormula1))
anv1 <- anova(legLmFull)
kable(anv1, caption = paste("Anova of full model by itself. Model:", myFormula1))
cat("\n\r")
anv2 <- anova(legLmFull, legLmRed)
kable(anv2, caption = paste("Anova of full vs reduced model. Formulas:", myFormula1, " Reduced:", myFormulaRed))

```