---
title: "Dispersal Simulation Results For Committee"
author: "Ruth Sharpe"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  word_document:
    reference_docx: StyleReference.docx


---

```{r include = FALSE}
knitr::opts_chunk$set(echo = FALSE, comment = "", message = FALSE, fig.height=18, fig.width=30)

mytheme <- theme_bw(base_size=50)  + theme(plot.title = element_text(vjust=2, size = 50), panel.margin= unit(0.75, "lines"),
		plot.margin=unit(c(3,1,1.5,1.2),"cm"), panel.border = element_rect(fill = NA, colour = "black", linetype=1, size = 1), legend.position="right", 
		legend.background = element_rect(fill="white", size=1, linetype="solid", colour ="black"), legend.text=element_text(size=50))
	
```

Size of dispersing population
=======================

vs. ad size and comp
--------------

```{r disPopSize}
df_DP <- subset(dis_ply, max_no_off == 8 & input_var == 0.2)

ggplot(data = df_DP, aes(x = Comp_meas , y = col_size_disp.mean, colour = as.factor(ad_dsp_fd))) + geom_point(size = 9) + geom_line(size = 2) + mytheme +
		ylab("Log Size of dispersing population") + scale_colour_discrete("Dispersal\nSize") + xlab("Competition Measure")

```

vs. offspring number and environment variation
----------------------

```{r disPopSize2}


df_DP2 <- subset(dis_ply, Comp_meas== 0.8 & ad_dsp_fd == 0.6)

ggplot(data = df_DP2, aes(x = input_var , y = col_size_disp.mean, colour = as.factor(max_no_off))) + geom_point(size = 9) + geom_line(size = 2) + mytheme +
		ylab("Log Size of dispersing population") + scale_colour_discrete("Number\noffspring") + xlab("Environmental Variation")



```

dispersal frequency
==============

```{r freqDisp}
p11

df_FD <- subset(dis_ply, input_var ==0)

ggplot(data = df_FD, aes(x = Comp_meas , y = MeanDispFreq, colour = as.factor(ad_dsp_fd))) + geom_point(size = 9) + geom_line(size = 2) + mytheme +
		ylab("Log Size of dispersing population") + scale_colour_discrete("Dispersal\nSize") + xlab("Competition Measure") + facet_grid(~max_no_off) +
		ggtitle("Number of offspring")
```


survival of population
===========

vs. comp vs adult disperal size
--------

```{r popSurv}

df_PS <- subset(dis_ply, max_no_off == 4 & input_var == 0.1)

ggplot(data = df_PS, aes(x = Comp_meas , y = log10(survival_all.mean), colour = as.factor(ad_dsp_fd))) + geom_point(size = 9) + geom_line(size = 2) + mytheme +
		ylab("Log average population survival") + scale_colour_discrete("Dispersal\nSize") + xlab("Competition Measure")


###
df_PS2 <- subset(dis_ply, max_no_off == 4)
ggplot(df_PS2, aes(x = input_var, y = log10(survival_all.mean), colour = as.factor(Comp_meas))) + geom_point(size = 9) + 
		facet_grid(~ad_dsp_fd)  + geom_line(size = 2) + mytheme + ylab("Log average population survival") + 
		scale_colour_discrete("Comp\nMeasure") + xlab("Environmental Variation") + ggtitle("Min Dispersal Size")

df_PS3 <- subset(dis_ply, max_no_off == 4 & ad_dsp_fd != 0.6 & ad_dsp_fd != 0.8 )


ggplot(df_PS3, aes(x = input_var, y = log10(survival_all.mean), colour = as.factor(Comp_meas))) + geom_point(size = 9) + 
		facet_grid(~ad_dsp_fd)  + geom_line(size = 2) + mytheme + ylab("Log average population survival") + 
		scale_colour_discrete("Comp\nMeasure") + xlab("Environmental Variation") + ggtitle("Min Dispersal Size")

```


extinct without dispersing
=====

```{r ExtinctNoDisp}

ggplot(df_PS2, aes(x = input_var, y = MeanPerDieNoDsp, colour = as.factor(Comp_meas))) + geom_point(size = 9) + 
		facet_grid(~ad_dsp_fd)  + geom_line(size = 2) + mytheme + ylab("Mean Percentage of populations") + 
		scale_colour_discrete("Comp\nMeasure") + xlab("Environmental variation") + ggtitle("Min Dispersal Size")


df_END <- subset(dis_ply, input_var == 0.1 & Comp_meas != 0.5 & ad_dsp_fd == 0.8)

ggplot(df_END, aes(x = Comp_meas, y = MeanPerDieNoDsp, colour = as.factor(max_no_off))) + geom_point(size = 10) + 
		geom_line(size = 4) + mytheme +  ylab("Mean Percentage of populations") + 
		xlab("Competition") + scale_colour_discrete("Number\noffspring") 

```

Metapopulation
=====

```{r metapop}


df_MT <- subset(dis_ply, input_var == 0.1)


ggplot(df_MT, aes(x = Comp_meas, y = log10(PopAge.Mean), colour = as.factor(ad_dsp_fd))) + geom_point(size = 9) + 
		facet_grid(~max_no_off)  +  ggtitle("") + geom_line(size = 2) + mytheme + ylab("Log max metapopulation age")


df_MT2 <- subset(dis_ply, max_no_off == 8)
ggplot(df_MT2, aes(x = input_var, y = log10(PopAge.Mean), colour = as.factor(Comp_meas))) + geom_point(size = 9) + 
		facet_grid(~ad_dsp_fd)  +  ggtitle("Dispersal Size") + geom_line(size = 2) + mytheme + ylab("Log max metapopulation age") +
		scale_colour_discrete("Comp") + xlab("Environment variation")


df_MT3 <- subset(dis_ply, max_no_off == 6 &  input_var == 0.1)
ggplot(df_MT3, aes(x = Comp_meas, y = log10(PopAge.Mean), colour = as.factor(ad_dsp_fd))) + geom_point(size = 9) + 
		 geom_line(size = 2)  + ylab("Log max metapopulation age") + mytheme + xlab("competition") + scale_colour_discrete("Dispersal\nSize")

```

