

---
title: "Leg Length vs Nest Size with sex and instar as numeric"
output:
  pdf_document:
    toc: true
author: "Ruth Sharpe"
date: "`r format(Sys.time(), '%d %B, %Y')`"
geometry: margin=1.5cm
header-includes:
    - \usepackage{caption}
---

\captionsetup[table]{labelformat=empty}

```{r docOptions, include = FALSE}
knitr::opts_chunk$set(echo = FALSE, comment = "", message = FALSE, error = FALSE)
	
```


AIC Values of all possible models with instar always included
====================

```{r AIC, results='asis',  echo = FALSE}
#pander options http://rapporter.github.io/pander/#general-options

outcome    <- c("logLeg")
predictors <- c("InstarNumber", "InstarNumber:InstarSex", "logCtFm:InstarNumber", "logCtFm:InstarNumber:InstarSex")
dataset    <- spidersMul

modTable <- allModelsAICWithSex(outcome, predictors, dataset)



row.names(modTable) <- NULL # removing row names

panderOptions('table.split.table', Inf)
panderOptions('round', 2)
panderOptions('keep.trailing.zeros', TRUE)
panderOptions('keep.line.breaks', TRUE)


pander(modTable,  row.names = NULL, justify = 'left', split.cells = c(1, 2, 61, 2))

## outputting lowest AIC model
lowestAICMod <- as.character(modTable$model[1])

formula    <- as.formula(lowestAICMod)

#cat("adding InstarNumber:InstarSex to the model, diff in AIC very small and sensible to have it in")

#formula <- update(formula, .~. + InstarNumber:InstarSex + (1|NestID))


formula <- update(formula, .~. + (1|NestID))

FullModel       <- lmer(formula, data = dataset, REML = FALSE)
	
```

\pagebreak

Checking full model fit
--------------------


```{r ModelFit, fig.height=4, fig.width=4}

model_Check(FullModel)


```
\pagebreak

Graph with full model superimposed
====================
 

```{r Graph, fig.height=7, fig.width=13}


cat("Model:", as.character(FullModel@call[2]), sep = '\n')

InstarGridGraph(dataset, "logLeg", "Leg Length - log transformed", "n", "", FullModel)

```




Statistics
====================
Note: There is no point testing instar number against leg length as it will vary of course, same with instar size


```{r Stats,  results='asis', echo = FALSE, comment = "", message = FALSE}

#logLeg ~ logCtFm + InstarNumber + logCtFm:InstarNumber + logCtFm:InstarNumber:InstarSex + InstarNumber:InstarSex (1 | NestID)

Test3WayInteraction <- c("Three way interaction", update(FullModel, . ~ . - logCtFm:InstarNumber:InstarSex))
TestInteraction2 <- c("Nest size x Instar Number", update(FullModel, . ~ . - logCtFm:InstarNumber - logCtFm:InstarNumber:InstarSex))
#TestInteractionSex <- c("Instar Number x Instar Sex", update(FullModel, . ~ . - InstarNumber:InstarSex - logCtFm:InstarNumber:InstarSex))
TestInstarAge <- c("Instar age", update(FullModel, . ~ . -InstarNumber - logCtFm:InstarNumber - logCtFm:InstarNumber:InstarSex - InstarNumber:InstarSex ))
TestNS <- c("NestSize", update(FullModel, . ~ . - logCtFm - logCtFm:InstarNumber:InstarSex - logCtFm:InstarNumber))

RedModels <- list(Test3WayInteraction, TestInteraction2, TestInstarAge, TestNS)

MRAnovaFun(FullModel, RedModels)

```
\pagebreak

Testing Individual Instars
--------------------


###As the three way interaction is significant testing instar individually



```{r IndInstars,  results='asis', echo = FALSE, comment = "", tab.cap = NULL, message = FALSE, warning = FALSE, hold = TRUE}


LMERS_fun <- function(myData) { # function to test individual instars 	
    lmFull <- lmer(logLeg ~  logCtFm + (1|NestID), data = myData)
    lmRed <- lmer(logLeg ~  + (1|NestID), data = myData)
    return(list(lmFull, lmRed))
	
    }


instarLMER <- dlply(dataset, .(Instar),        
		function(x) LMERS_fun(x))


results <- lapply(instarLMER, FUN = function(x) anova(x[[1]], x[[2]], refit
= TRUE))

sig <- lapply(results, FUN = function(x) ifelse(x[,8][2] <= 0.05, " * SIGNIFICANT *", "not significant"))



cat("note: pops up saying 'refitting model(s) with ML (instead of REML)'", "but if make anova refit = FALSE results don't make sense", sep = '\n')

kable(results$Adult, caption = paste("Adult", sig$Adult))

kable(results$Sub2, caption = paste("Sub2", sig$Sub2))

kable(results$Sub1, caption = paste("Sub1", sig$Sub1))

kable(results$Juv4, caption = paste("Juv4", sig$Juv4))

kable(results$AdMale, caption = paste("AdMale", sig$AdMale))

kable(results$SubMale, caption = paste("SubMale", sig$SubMale))

ggplot(subset(dataset, InstarNumber == 6 | InstarNumber == 5), aes(x = logCtFm, y = logLeg, colour = InstarSex )) + 
		geom_point() + geom_smooth(method = "lm", se = FALSE) + facet_wrap(~InstarNumber, scales = "free") +
		mytheme
	
```



Instar Age x nest size Interaction Graph
===========
 

```{r, fig.height=7, fig.width=13}

#newMod <- update(FullModel,  . ~ . - logCtFm)
cat("Model:", as.character(FullModel@call[2]), sep = '\n')

a_predictDF <- expand.grid(logCtFm = seq(min(dataset$logCtFm), max(dataset$logCtFm), by = 0.1), 
		InstarNumber = c(4, 5, 6, 7), InstarSex = c("M", "F"), NestID = c("44.4EX12"))

a_predictDF <- expand.grid(logCtFm = seq(min(dataset$logCtFm), max(dataset$logCtFm), by = 0.1), 
		InstarNumber = c(4, 5, 6, 7), InstarSex = c("F"), NestID = c("44.4EX12"))


a_predictDF$lmrPrd <- predict(FullModel, a_predictDF)

a_predictDF <- merge(a_predictDF, InstarLookUp, by = c("InstarNumber", "InstarSex"))

#a_predictDF <- ddply(a_predictDF, c("Instar"), transform, x.std = scale(lmrPrd, scale = TRUE, center = TRUE))

a_predictDF <- ddply(a_predictDF, c("Instar"), transform, minValue = min(lmrPrd))

a_predictDF$scaled <- a_predictDF$lmrPrd - a_predictDF$minValue
# don't actually have to scale, just need to minus the min value from each value

a_predictDF <- ddply(a_predictDF, c("Instar"), transform, mean = mean(scaled))
a_predictDF$scaled2 <- a_predictDF$scaled/a_predictDF$mean

ggplot(data = a_predictDF, aes(x = logCtFm, y = scaled2, colour = as.factor(InstarNumber))) + geom_line(size = 1) + mytheme +
		ylab("Scaled Predicted Leg Length") + xlab("Log Count Females") + scale_colour_discrete(name = "Instar Age")


```

