

---
title: "Variance in Leg vs Nest Size Instar As Number"
author: "Ruth Sharpe"
date: "Run on `r format(Sys.time(), '%d %B, %Y')`"
geometry: margin=1cm

---

```{r dataImport,  include = FALSE}
knitr::opts_chunk$set(echo = FALSE, comment = "", message = FALSE)

minN <- 2
dataset <- subset(legVar, N > minN)
totSpis <- sum(dataset$N)
dataset$lmrWgts <- dataset$N/ totSpis





```

AIC Values of all possible models with instar included and sample size as weight
------------------
Rows removed with `r minN` or fewer data points 

```{r kable, results='asis',  echo = FALSE}
#pander options http://rapporter.github.io/pander/#general-options




outcome    <- c("relativeVar")
predictors <- c("InstarNumber", "InstarNumber:InstarSex", "logCtFm:InstarNumber", "logCtFm:InstarNumber:InstarSex", 
		"I(InstarNumber^2)", "I(InstarNumber^2):InstarSex", "I(InstarNumber^2):InstarSex:logCtFm")


modTable <- allModelsAICWithSex(outcome, predictors, dataset, "y") # weights included if "y"

row.names(modTable) <- NULL # removing row names

panderOptions('table.split.table', Inf)
panderOptions('round', 2)
panderOptions('keep.trailing.zeros', TRUE)
panderOptions('keep.line.breaks', TRUE)


pander(modTable,  row.names = NULL, justify = 'left', split.cells = c(1, 2, 61, 2))

lowestAICMod <- as.character(modTable$model[1])

FullFormula    <- as.formula(lowestAICMod)
FullModel       <- lmer(FullFormula, data = dataset, weights = lmrWgts, REML = FALSE)
	
```

Checking full model fit
--------------------


```{r ModelFit, fig.height=3, fig.width=3}

model_Check(FullModel)

```
\pagebreak

Graphs
====================

Leg Variance against nest size
-----------
 
note: blue line just lm model
```{r, fig.height=8, fig.width=12, echo = FALSE}


InstarGridGraph(dataset, "relativeVar", "Variance in leg", "n", "", FullModel, "y")

```

Graph of leg variance against instar
--------

```{r legVarInstar, fig.height=6, fig.width=8, echo = FALSE}
ggplot(data = dataset, aes(x = as.factor(InstarNumber), y = relativeVar, fill = InstarSex)) +
	labs(x = "Instar") + labs(y = "Variance in leg") + geom_boxplot() + mytheme

```
\pagebreak

Statistics using model with the almost lowest AIC as full model
====================


```{r Stats,  results='asis', echo = FALSE , comment = "", message = FALSE, warning = FALSE}


TestNS <- c("Testing NestSize",  update(FullModel, .~. -logCtFm - logCtFm:InstarNumber))
InstModel <- c("Testing Instar age", update(FullModel, . ~ . - ( InstarNumber + InstarNumber:InstarSex + logCtFm:InstarNumber + I(InstarNumber^2))))


RedModels <- list(TestNS, InstModel)

MRAnovaFun(FullModel, RedModels)

#stargazer(anova(FullModel), summary = FALSE, title = "Anova of full model alone", header = FALSE)

```



Testing individual instar numbers
--------------------

```{r IndInstars,  results='asis', echo = FALSE, comment = "", tab.cap = NULL, message = FALSE, warning = FALSE, hold = TRUE}


LMERS_fun <- function(instarData) { # function to test individual instars 	
	instarData$lmrWgts <- instarData$N/ sum(instarData$N)
    lmFull <- lm(relativeVar ~  logCtFm, weights = lmrWgts, data = instarData)
    lmRed <- lm(relativeVar ~ 1, weights = lmrWgts, data = instarData)
    return(list(lmFull, lmRed))
	
    }


instarLM <- dlply(dataset, .(Instar),        
		function(x) LMERS_fun(x))


results <- lapply(instarLM, FUN = function(x) anova(x[[1]], x[[2]]))



sig <- lapply(results, FUN = function(x) ifelse(x[,6][2] <= 0.05, " * SIGNIFICANT *", "not significant"))


kable(results$'7', caption = paste("Adult - age 7", sig$'7'))

kable(results$'6', caption = paste("Sub2 and Adult Males - age 6", sig$'6'))

kable(results$'5', caption = paste("Sub1 and sub males- age 5", sig$'5'))

kable(results$'4', caption = paste("Juv4 - age 4", sig$'4'))

	
```
