

---
title: "Biomass by Nest Size"
author: "Ruth Sharpe"
date: "`r format(Sys.time(), '%d %B, %Y')`"
geometry: margin=1.5cm

---


```{r dataImport,  include = FALSE}
knitr::opts_chunk$set(echo = FALSE, comment = "", message = FALSE)


```



Biomass per capita calculated as insect biomass over total number of adult females
====================

Checking AICs of two models
-------------------

```{r AICs}

Model <- lmer(BiomsPerAdFm ~ log10AdFm + (1|ColonyID) + (1|Date), data = Biomass, REML = FALSE)


cat("Biomass per adult female =  nest size + (1|ColonyID) + (1|Date)")
cat("AIC:", AIC(Model))

cat("__________")
# instar squared model
ModelSqr <- lmer(BiomsPerAdFm ~ log10AdFm + I(log10AdFm^2) +  (1|ColonyID) + (1|Date), data = Biomass, REML = FALSE)
cat("Biomass per adult female =  nest size + nest size squared +  (1|ColonyID) + (1|Date)")
cat("AIC:", AIC(ModelSqr))

```

Testing full against reduced model
-------

Model without square value has the lowest AIC

```{r stats,  results='asis'}

RedModel <- lmer(BiomsPerAdFm ~ (1|ColonyID) + (1|Date), data = Biomass, REML = FALSE)

anv1 <- anova(Model, RedModel)

myTitle <- anvTitle(anv1, "Lowest AIC model Against Reduced Model")

myNote <- "Full: log10AdFm + (1 | ColonyID) + (1 | Date) vs. Reduced: (1 | ColonyID) + (1 | Date)"

stargazer(anv1, summary = FALSE, title = myTitle, header = FALSE, notes = myNote)

```



Checking full model fit
--------------------


```{r ModelFit, fig.height=3, fig.width=3}

model_Check(Model)

```

Graph of biomass against nest size 
====================


```{r GraphBiomass, fig.height=4, fig.width=5.5}

plot <- ggplot(data = Biomass, aes(x = log10AdFm, y = BiomsPerAdFm)) + geom_point()
plot <- plot + xlab("Nest size - number of adult females") + ylab("Prey biomass per adult female") + mytheme

Vis_fit <- (visreg(Model, "log10AdFm", plot = FALSE))$fit						
plot <- plot +  geom_line(data = Vis_fit, aes(x = log10AdFm, y= visregFit))
plot

```

