

---
title: "Individual Condition vs Nest Size with sex and instar as numeric value"
author: "Ruth Sharpe"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  pdf_document:
    toc: true
geometry: margin=1.5cm
header-includes:
    - \usepackage{caption}
---

\captionsetup[table]{labelformat=empty}

```{r include = FALSE}
knitr::opts_chunk$set(echo = FALSE, comment = "", message = FALSE)
	
```

AIC Values of all possible models with instar always included
====================

note: InstarNumber is numeric

```{r kable, results='asis',  echo = FALSE, warnings = FALSE, message = FALSE}

myData <- spidersMul


outcome    <- c("condResiduals")
predictors <- c("InstarNumber", "InstarNumber:InstarSex", "logCtFm:InstarNumber", "logCtFm:InstarNumber:InstarSex")

modTable <- allModelsAICWithSex(outcome, predictors, myData)

lowestAICMod <- as.character(modTable$model[1])
formula    <- as.formula(lowestAICMod)
FullModel    <- lmer(formula, data = myData, REML = FALSE)


row.names(modTable) <- NULL # removing row names

panderOptions('table.split.table', Inf)
panderOptions('round', 2)
panderOptions('keep.trailing.zeros', TRUE)
panderOptions('keep.line.breaks', TRUE)


pander(modTable,  row.names = NULL, justify = 'left', split.cells = c(1, 2, 61, 2))


lowestAICMod <- as.character(modTable$model[1])

formula    <- as.formula(lowestAICMod)
FullModel       <- lmer(formula, data = myData, REML = FALSE)


	
```

\pagebreak

Checking full model fit
--------------------


```{r ModelFit, fig.height=4, fig.width=4}

model_Check(FullModel)



```


Graph with lowest AIC model superimposed
====================
 

```{r, fig.height=7, fig.width=13}


cat("Model:", as.character(FullModel@call[2]), sep = '\n')

InstarGridGraph(myData, "condResiduals", "Condition", "n", "", FullModel, "y")

```

\pagebreak


Statistics using model with lowest AIC
====================


```{r Stats,  results='asis', echo = FALSE, comment = "", }

########### Continune from here!


TestInteraction  <- c("Testing Interaction Term nest size * instar", lmer(condResiduals ~ logCtFm +  (1|NestID), data = myData, REML = FALSE))
TestNestSize <- c("Testing Nest Size plus nest size interactions", lmer(condResiduals ~  (1|NestID) , data = myData, REML = FALSE))


RedModels <- list(TestInteraction, TestNestSize)

MRAnovaFun(FullModel, RedModels)

```

Testing individual instar numbers
--------------------

```{r IndInstars,  results='asis', echo = FALSE, comment = "", tab.cap = NULL, message = FALSE, warning = FALSE, hold = TRUE}


LMERS_fun <- function(myData) { # function to test individual instars 	
    lmFull <- lmer(condResiduals ~  logCtFm + (1|NestID), data = myData)
    lmRed <- lmer(condResiduals ~ (1|NestID), data = myData)
    return(list(lmFull, lmRed))
	
    }


instarLMER <- dlply(myData, .(InstarNumber),        
		function(x) LMERS_fun(x))


results <- lapply(instarLMER, FUN = function(x) anova(x[[1]], x[[2]], refit
= TRUE))

cat("note: pops up saying 'refitting model(s) with ML (instead of REML)'", "but if make anova refit = FALSE results don't make sense", sep = '\n')

kable(results$'7', caption = "Adult - significat!")

kable(results$'6', caption = "Sub2 and Adult Males")

kable(results$'5', caption = "Sub1 and sub males")

kable(results$'4', caption = "Juv4")

	
```
