

---
title: "Individual Condition vs Nest Size"
author: "Ruth Sharpe"
date: "`r format(Sys.time(), '%d %B, %Y')`"
geometry: margin=1.5cm
header-includes:
    - \usepackage{caption}
---

\captionsetup[table]{labelformat=empty}

```{r include = FALSE}
knitr::opts_chunk$set(echo = FALSE, comment = "", cache.lazy = TRUE)
	
```


AIC Values of all possible models with instar always included
====================

note: InstarNumber is a numeric value denoting age

```{r kable, results='asis',  echo = FALSE, warnings = FALSE, message = FALSE}

myData <- spidersMul


outcome    <- c("condResiduals")
predictors <- c("logCtFm", "logCtFm:InstarNumber", "InstarSex:InstarNumber", "InstarSex:logCtFm")
dataset    <- myData

modTable <- allModelsAICWithSex(outcome, predictors, dataset)


row.names(modTable) <- NULL # removing row names

panderOptions('table.split.table', Inf)
panderOptions('round', 2)
panderOptions('keep.trailing.zeros', TRUE)
panderOptions('keep.line.breaks', TRUE)


pander(modTable,  row.names = NULL, justify = 'left', split.cells = c(1, 2, 61, 2))
	
```




Graph with lowest AIC model superimposed
====================
 

```{r, fig.height=7, fig.width=13}

FullModel <- lmer(condResiduals ~ logCtFm + InstarNumber + InstarSex + logCtFm:InstarSex +
				(1|NestID), data = myData, REML = FALSE)


cat("Model:", as.character(FullModel@call[2]), sep = '\n')

InstarGridGraph(myData, "condResiduals", "Condition", "n", "", FullModel)

```

\pagebreak


Statistics using model with lowest AIC
====================


```{r Stats,  results='asis', echo = FALSE, comment = "", }

########### Continune from here!


TestInteraction  <- c("Testing Interaction Term nest size * sex", lmer(condResiduals~  logCtFm + Instar + (1|NestID)  , data = myData, REML = FALSE))
TestInstar <- c( "Testing Instar Term", lmer(condResiduals~  logCtFm +  (1|NestID)  , data = myData, REML = FALSE))
TestNestSize <- c("Testing Nest Size", lmer(condResiduals ~  Instar +  (1|NestID)  , data = myData, REML = FALSE))


RedModels <- list(TestNestSize, TestInstar, TestInteraction)

MRAnovaFun(FullModel, RedModels)

```
\pagebreak

Testing Individual Instars
====================
###As the interaction is significant testing instar individually



```{r IndInstars,  results='asis', echo = FALSE, comment = "", tab.cap = NULL, message = FALSE}


LMERS_fun <- function(myData) { # function to test individual instars 	
    lmFull <- lmer(condResiduals ~  logCtFm + (1|NestID), data = myData)
    lmRed <- lmer(condResiduals ~  + (1|NestID), data = myData)
    return(list(lmFull, lmRed))
	
    }


instarLMER <- dlply(myData, .(Instar),        
		function(x) LMERS_fun(x))


results <- lapply(instarLMER, FUN = function(x) anova(x[[1]], x[[2]], refit
= TRUE))

cat("note: pops up saying 'refitting model(s) with ML (instead of REML)'", "but if make anova refit = FALSE results don't make sense", sep = '\n')

kable(results$Adult, caption = "Adult")

kable(results$Sub2, caption = "Sub2")

kable(results$Sub1, caption = "Sub1")

kable(results$Juv4, caption = "Juv4")

kable(results$AdMale, caption = "AdMale")

kable(results$SubMale, caption = "SubMale")
	
```

