

---
title: "Individual Condition vs Nest Size with sex and instar as numeric value"
author: "Ruth Sharpe"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  pdf_document:
    toc: true
geometry: margin=1.5cm
header-includes:
    - \usepackage{caption}
---

\captionsetup[table]{labelformat=empty}

```{r include = FALSE}
knitr::opts_chunk$set(echo = FALSE, comment = "", message = FALSE)
	
```
\pagebreak

AIC Values of all possible models with instar always included
====================

note: InstarNumber is numeric

```{r kable, results='asis',  echo = FALSE, warnings = FALSE, message = FALSE}

myData <- spidersMul


outcome    <- c("condResiduals")
predictors <- c("logCtFm", "logCtFm:InstarNumber:InstarSex", "logCtFm:InstarNumber", "InstarSex:InstarNumber", "InstarSex:logCtFm")
dataset    <- myData

modTable <- allModelsAICWithSex(outcome, predictors, dataset)


row.names(modTable) <- NULL # removing row names

panderOptions('table.split.table', Inf)
panderOptions('round', 2)
panderOptions('keep.trailing.zeros', TRUE)
panderOptions('keep.line.breaks', TRUE)


pander(modTable,  row.names = NULL, justify = 'left', split.cells = c(1, 2, 61, 2))
	
```



Graph with lowest AIC model superimposed
====================
 

```{r, fig.height=7, fig.width=13}

FullModel <- lmer(condResiduals ~ logCtFm + InstarNumber + InstarSex + logCtFm:InstarSex +
				(1|NestID), data = myData, REML = FALSE)


cat("Model:", as.character(FullModel@call[2]), sep = '\n')

InstarGridGraph(myData, "condResiduals", "Condition", "n", "", FullModel)

```




Statistics using model with lowest AIC
====================


```{r Stats,  results='asis', echo = FALSE, comment = "", }

########### Continune from here!

FullModel <- lmer(condResiduals ~ logCtFm + InstarNumber + InstarSex + logCtFm:InstarSex +
				(1|NestID), data = myData, REML = FALSE)

TestInteraction  <- c("Testing Interaction Term nest size * sex", lmer(condResiduals ~ logCtFm + InstarNumber + InstarSex  + (1|NestID), data = myData, REML = FALSE))
TestInstar <- c( "Testing Instar Number", lmer(condResiduals ~ logCtFm + InstarSex + logCtFm:InstarSex + (1|NestID), data = myData, REML = FALSE))
TestSex <- c("Testing Instar Sex", lmer(condResiduals ~ logCtFm + InstarNumber  +  (1|NestID), data = myData, REML = FALSE))
TestNestSize <- c("Testing Nest Size", lmer(condResiduals ~  InstarNumber + InstarSex  + (1|NestID) , data = myData, REML = FALSE))


RedModels <- list(TestInteraction, TestInstar, TestSex, TestNestSize)

MRAnovaFun(FullModel, RedModels)

```
